name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run CMake
        uses: lukka/run-cmake@v2.5
        with: 
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          buildDirectory: ${{ github.workspace }}/build
      - name: Test
        run: cd ${{ github.workspace }}/build && ctest
