name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run CMake
        uses: lukka/run-cmake@v2.5
        with: 
          cmakeListsTxtPath: ${{ github.repository }}/CMakeLists.txt
          buildDirectory: ${{ github.repository }}/build
      - name: Build
        run: cd ${{ github.repository }} && make
      - name: Test
        run: cd ${{ github.repository }} && make test
