name: C/C++ CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/main.yml'
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/main.yml'
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'

jobs:
  build:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Run Cmake --build
        run: cmake --build build

      - name: Run CTest
        run: cd ./build && ctest -V
