name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/main.yml'
      - '**.cpp'
      - '**.hpp'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/main.yml'
      - '**.cpp'
      - '**.hpp'
      - 'CMakeLists.txt'

jobs:
  build:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@main
        with: 
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          buildDirectory: ${{ github.workspace }}/build
          useVcpkgToolchainFile: false

      - name: Run CTest
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: cd ${{ github.workspace }}/build && ctest