name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{runner.workspace}}/build
          build-type: Release
          cxx: g++
          run-test: true
